### PR TITLE
Change namespace use the GeoSPARQL ontology

### PR DESCRIPTION
**Pull request by jyucsiro**
As per https://github.com/opengeospatial/SELFIE/issues/96

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Thanks! Note that this change also needs to get applied over in the newer SELFIE contexts here: https://github.com/opengeospatial/ELFIE/tree/master/docs/contexts/elfie-2 Would you like to do that or I can merge and take care of it.

**Comment by dblodgett-usgs** [comment]
I take that back. Looks like the topology context hasn't been moved in there yet.
It was copied here: https://github.com/opengeospatial/ELFIE/tree/master/docs/contexts/elfie-1 but I think the plan was to keep those as is for posterity.

**Comment by jyucsiro** [comment]
> Thanks! Note that this change also needs to get applied over in the newer SELFIE contexts here: https://github.com/opengeospatial/ELFIE/tree/master/docs/contexts/elfie-2 Would you like to do that or I can merge and take care of it.

I'm happy to do that - so confirming that SELFIE contexts need updating in here?
https://github.com/opengeospatial/ELFIE/tree/master/docs/contexts/elfie-2

**Comment by dblodgett-usgs** [comment]
No need. I think we are all good until we make more changes later.

**Pull request merged**
